export function getPdfMargins(marginPreset) {
  const marginMap = {
    compact: { top: "18mm", bottom: "18mm", left: "12mm", right: "12mm" },
    normal: { top: "30mm", bottom: "26mm", left: "18mm", right: "18mm" },
    spacious: { top: "36mm", bottom: "30mm", left: "22mm", right: "22mm" }
  };

  return marginMap[marginPreset] || marginMap.normal;
}

export function getFontFamily(fontChoice) {
  switch (fontChoice.toLowerCase()) {
    case "roboto":
      return `"Roboto", "Segoe UI", Arial, sans-serif`;
    case "serif":
    case "times":
      return `"Times New Roman", Times, serif`;
    default:
      return `system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Arial, sans-serif`;
  }
}

export function buildDocumentHTML({ htmlToRender, finalTheme, fontFamily, borderColor }) {
  const background = finalTheme === "light" ? "#ffffff" : "#020617";
  const textColor = finalTheme === "light" ? "#020617" : "#e5e7eb";
  const preBg = finalTheme === "light" ? "#f8fafc" : "#0b1220";
  const thBg = finalTheme === "light" ? "#eef2ff" : "#020617";

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8" />
  <style>
    @page { margin: 0; }

    body {
      margin: 0;
      padding: 0;
      background: ${background};
      color: ${textColor};
      font-family: ${fontFamily};
      line-height: 1.5;
      -webkit-print-color-adjust: exact;
      print-color-adjust: exact;
    }

    .pdf-root {
      width: 100%;
      box-sizing: border-box;
    }

    .page-break {
      page-break-before: always;
    }

    pre {
      background: ${preBg};
      color: inherit;
      border: 1px solid ${borderColor};
      border-radius: 10px;
      padding: 12px 14px;
      overflow-x: auto;
      font-size: 13px;
      line-height: 1.45;
      page-break-inside: avoid;
    }

    code {
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", monospace;
    }

    h1, h2, h3 { page-break-after: avoid; }

    ul, ol { padding-left: 22px; }
    li { margin: 4px 0; }

    table {
      width: 100%;
      border-collapse: collapse;
      margin: 10px 0;
    }

    th, td {
      border: 1px solid ${borderColor};
      padding: 6px 8px;
      text-align: left;
    }

    th { background: ${thBg}; }
  </style>
</head>
<body>
  <div class="pdf-root">${htmlToRender}</div>
</body>
</html>
  `;
}

export function buildPdfOptions({
  finalPageSize,
  finalOrientation,
  headerEnabled,
  footerEnabled,
  includeDateTime,
  textColor,
  pdfMargins
}) {
  const displayHeaderFooter = headerEnabled || footerEnabled || includeDateTime;
  const nowString = includeDateTime ? new Date().toLocaleString() : "";

  const headerTemplate = headerEnabled || includeDateTime
    ? `
      <div style="font-size:9px;width:100%;text-align:center;color:${textColor};padding-top:6px;">
        ${includeDateTime ? nowString : ""}
      </div>
    `
    : "<div></div>";

  const footerTemplate = footerEnabled
    ? `
      <div style="font-size:9px;width:100%;display:flex;justify-content:space-between;padding:0 18mm;color:${textColor};">
        <span>Generated by MD -> Perfect PDF</span>
        <span>Page <span class="pageNumber"></span> / <span class="totalPages"></span></span>
      </div>
    `
    : "<div></div>";

  return {
    format: finalPageSize,
    landscape: finalOrientation === "landscape",
    printBackground: true,
    displayHeaderFooter,
    headerTemplate,
    footerTemplate,
    margin: pdfMargins
  };
}
